### ISSUE TITLE
dbms_output / timing

### ISSUE THREAD

**Issue by MGralike** [OraOpenSource/Logger#100]
When using DBMS_OUTPUT please use the following to set the buffer:

DBMS_OUTPUT.ENABLE (buffer_size => NULL); 

This to avoid 

ORA-06502: PL/SQL: numeric error or error in value : character string buffer too small.

and/or... get rid of the '>>>' output "functionality" in the timing section (aka split functionality from output). When accidentally getting into loops and/or unexpected processing (thus testing with start and stop timing), the following might occur when building up insightful output

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320077] - 00:00:00.002421
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320078] - 00:00:00.002422
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320079] - 00:00:00.002423
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320080] - 00:00:00.002433
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320081] - 00:00:00.003421
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320082] - 00:00:00.002321
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320083] - 00:00:00.002433
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>  STOP : Backup(commentaar): WGJN.BACKUP[ ID:6320084] - 00:00:00.058320

I hope you get the idea...it will end up in a buffer too small error.

Thanks

Marco

**Comment by MGralike** [comment]
See screenshot possible effects and cause ">>>"
![capture](https://cloud.githubusercontent.com/assets/8393411/7177127/76cbed90-e424-11e4-9410-b703156d1006.PNG)

**Comment by martindsouza** [comment]
What are you calling exactly that triggers all the calls to `dbms_output`?

**Comment by MGralike** [comment]
Logger_log.start_timing(....) if I remember correctly 

Send via mobile phone.

On Apr 16, 2015, at 22:58, martindsouza <notifications@github.com> wrote:

What are you calling exactly that triggers all the calls to dbms_output?

**Comment by martindsouza** [comment]
I just looked in `time_start` and didn't find any references to `dbms_output`. I actually went through the entire package and the ones that were there don't have anything to do with timing. What version of Logger are you running? Please run the following query to find out:

```sql
select *
from logger_prefs
where pref_name = 'LOGGER_VERSION'
```

**Comment by MGralike** [comment]
Sorry for the delay. Downloaded the latest master code Martin. 

I have "issues" with

        if g_running_timers > 1 then
          l_pad := lpad(' ',g_running_timers,'>')||' ';
        end if;

- If unexpectedly (especially in test circumstances) this gets caught up in a loop, you get the >>>>>>>>>>>>>>>>>>>... phenomena. 
- This will, did, fill up beyond maximum of column text in logger_logs
- Separate please functionality & output. People, I think are interested in the time, not the way it is displayed
- the >, >>, >>> is not bulletproof. I have seen displays where ">>" etc is shown were it should have been, for example, ">"

As a precaution with DBMS_OUTPUT, you go for sure, regarding possible buffer issues in the logger code, using DBMS_OUTPUT.ENABLE (buffer_size => NULL); 

So yes, it is actually 2 issues. Sorry for not being clear on that.

**Comment by martindsouza** [comment]
They're various tickets open with Timers and I think we're going to need to revisit the entire mechanism to see what works and what doesn't to simplify the call for developers and output bugs (as you highlighed with the `>`.  On that note, do you have any other suggestions for the timing procedures?

As for the calls to `DBMS_OUTPUT`, as I mentioned I can't find where in the code we do this outside of our own development debugging code (wrapped in conditional compilation: `$if $$logger_debug $then`) and in the call to `logger.status`. Can you please let me know where it is being called that is causing an issue.

Regardless, I agree that if we do use end up using `DBMS_OUTPUT` as a primary output in the future we'll call `DBMS_OUTPUT.ENABLE (buffer_size => NULL);`

**Comment by MGralike** [comment]
I ended up using, temporarily outside my logger framework (snik), Adrian Billington's (/Steven Feuerstein's) "Timer" package....

http://www.oracle-developer.net/content/utilities/timer.sql

Ah, sorry, didn't notice the conditional  "$if $$logger_debug $then" compilation wrappers. Than it might be it was triggered by something in my code, triggered by the >>>>>>>>>>>>>>>>>>... phenomenon. Anyway, the latter issue, caused me not using the timer functionality currently (although it made it very very clear I had a loop issue ;-)

Thx

:-)

**Comment by martindsouza** [comment]
I was just updating some of the timing code. Regarding the `>>>>` output, timers are meant to be pushed/popped from an array. The `>>>>` output is to make it an easier read. Here's how it is mean to be displayed:

```sql
START: foo
> START: bar
>> START: zoo
>> STOP : zoo - 00:00:00.366896
> STOP : bar - 00:00:00.727166
STOP : foo - 00:00:01.133554
```

As you can see it makes it easy to see the indentation and tree like structure. If you have a lot of timers within one another than the `>>>` indentation will get very large.

One other thing that may help, is for you to reset the timers before running your test procedures. Example: `logger.time_reset;`
