### ISSUE TITLE
Modify TOCHAR function for BOOLEAN

### ISSUE THREAD

**Issue by whenothers** [OraOpenSource/Logger#119]
Here's a change proposal for
`function tochar(p_val in boolean) return varchar2`

Instead of
`return case when p_val then 'TRUE' else 'FALSE' end;`

I'd alter that line to
`return case p_val when true then 'TRUE' when false then 'FALSE' else to_char(NULL) end;`

**Comment by martindsouza** [comment]
Good idea. Perhaps a slight change:

`return case p_val when true then 'TRUE' when false then 'FALSE' else 'NULL' end;`

This way it will explicitly state the word 'NULL' rather than being empty. There may be different views on this approach but this way it's specific that the boolean has not yet been defined.

Did you want to submit a pull request with the change?

**Comment by whenothers** [comment]
I was thinking about literal NULL, too, but in case of VARCHAR, NUMBER, DATE (etc.) there's no literal NULL returned either. We would have to change all other places as well to remain consistent.

> pull request...?

Not familiar with GIT yet, and tax declaration 2014 comes first :-)

**Comment by martindsouza** [comment]
Ok I agree with you on the null being blank (not the word "NULL").

As for GIT, part of goals for the OraOpenSource project is to get others familiar with open source development and Git. Here's a great document on how to make a pull request: https://help.github.com/articles/using-pull-requests/

When you have some time (after your taxes!), do you mind making this change? It's a small change and a good thing to learn/practice a pull request.

Thanks.

**Comment by whenothers** [comment]
With my own LOGGER package (see my comment on talkapex.com of today), I additionaly generate a method call wrapped in a BEGIN ... END block (using positional notation) so that the developer can immediately re-execute the whole statement. That's where these literal NULL values come into play. Example:
`-- Rerun the statement as of 2015-05-27 16:23:05`
`BEGIN`
`  my_procedure_call (`
`    i_param1 => 17`
`   ,i_param2 => NULL`
`  );`
`END;`

These functions of mine are called PRINT as compared to TOCHAR and they do care about formatting.
