### ISSUE TITLE
Allow for namespace / type in logger_prefs

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/Logger#127]
#104 (introduction of 3rd party plugins) highlights the need to expand the custom preference options. There will now be 3 types of preferences for the `logger_prefs` table:

- Logger prefs: these are managed and controlled by Logger's APIs. Names can be anything as long as they don't conflict with the previous for the other types of preferences (below).
- Custom prefs: developers can add what ever they want as long as it starts with `CUST_`
- 3rd Party Plugins: for 3rd party plugins (not to be confused with Logger's plugin support) should have their own name space that does not conflict with either of the two above. Each plugin will need to "register" a common and unique prefix for `pref_name`. For example `<common>_<unique>_<prefname>`. Example: `3PP_MYPLUG_EMAIL`.

Linked to #103

**Comment by barsema** [comment]
I would recommend to introduce namespaces in the prefs and not rely on naming conventions.
so extend the pref table with a `DOMAIN` column or `NAMESPACE`
The main logger prefs could be in the `MAIN` namespace, custom in `CUSTOM` namespace and the plugin preferences could use the plugin name.

**Comment by martindsouza** [comment]
Good idea and solves another issue with the current pref of `PLUGIN_FN_ERROR` and 3rd party plugins.

Regarding 3rd party plugins, do you still think they should be prefixed with a unique code? For example
```sql
NAMESPACE |  PREF_NAME  | PREF_VALUE

PLUG      | SYSLOG_ABC | Some value
```

Where `SYSLOG_` would be the prefix for the plugin that you developed?

**Comment by barsema** [comment]
Well why be stingy with the namespaces? I would suggest to give each plugin its own namespace

so 
```
NAMESPACE | PREF_NAME   | PREF_VALUE
MAIN      | VERSION     | 3.2.0
CUSTOM    | WHATEVER    | somthing
SYSLOG    | SEVER       | localhost
TWITTER   | ACCOUNT     | @barsema
```

off course then we need to support  daisy chaining plugins :-)

**Comment by martindsouza** [comment]
Instead of namespace I'll be calling it `PREF_TYPE` where `LOGGER` is a reserved word.

**Comment by martindsouza** [comment]
@barsema I just added the new column `logger_prefs.pref_type`. Do you mind given it a test (see releases/3.1.0_beta.zip)?
