### ISSUE TITLE
Change version number to Number (Not varchar2)

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/Logger#129]
Can't do conditional compilation on strings, need to use numbers instead. See http://nuijten.blogspot.nl/2015/07/conditional-compilation-and-static.html for details.

Will need to consider how to modify the build script as it currently does a replace on the string `x.x.x` for the version number.

**Comment by martindsouza** [comment]
Comments from Alex:

What I think can work is the following:
g_major_version constant pls_integer := x;
g_minor_version constant pls_integer := x;
g_patch_version constant pls_integer := x;
g_beta_version constant varchar2 := 'x';
g_logger_version constant varchar2 (50) := g_major_version||'.'|| g_minor_version||'.'||g_patch_version||'_'||g_beta_version

That way if someone were dependent on g_logger_version, it would still be there and not break anything. With a case statement to ex/include the beta suffix.

**Comment by martindsouza** [comment]
Another idea (and still needs to be tested) would be to create a function that could pass in a version number. It would return true/false if the current version is LTE that version. @alexnuijten what do you think?

Ex: logger.ver_lte('3.1.2')

Would need to test with conditional compilation. Again this is just an idea.

**Comment by alexnuijten** [comment]
Nice idea, however it doesn't work:
4/8	 PLS-00174: a static boolean expression must be used

**Comment by martindsouza** [comment]
@alexnuijten this will be in the next version `3.2.0` as `g_logger_version_major/minor/patch`
