### ISSUE TITLE
ORA-1031 on install

### ISSUE THREAD

**Issue by miklpotter** [OraOpenSource/Logger#136]
when installing, you may get an ORA-1031 when executing DBMS_UTILITY, even if you have execute granted.

if this occurs, you need to explicitly grant select on a sys table
`grant select on sys.v_$parameter to logger_user`

I think it would be worth including this into the Install doco, or notating the grant as a pre-requisite

Error starting at line : 10 in command -
```plsql
declare
  parnam varchar2(256);
  intval binary_integer;
  strval varchar2(500);
  partyp binary_integer;
begin
  partyp := dbms_utility.get_parameter_value('plsql_ccflags',intval, strval);

  if strval is not null then
    strval := ',' || strval;
  end if;
  :cur_plsql_ccflags := strval;
end;
Error report -
ORA-01031: insufficient privileges
ORA-06512: at "SYS.DBMS_UTILITY", line 140
ORA-06512: at line 7
01031. 00000 -  "insufficient privileges"
*Cause:    An attempt was made to perform a database operation without
           the necessary privileges.
*Action:   Ask your database administrator or designated security
           administrator to grant you the necessary privileges```

**Comment by martindsouza** [comment]
@miklpotter thanks for submitting issue and including a working around.

I'm going to re-evaluate the need for resetting the `plsql_ccflags` variable to get around the `currently_installing` issue in the `logger_prefs` trigger. If more people are having this issue I'll look at applying a patch for 3.1.1, if not it'll be part of 3.2.0.

**Comment by martindsouza** [comment]
@miklpotter I have the fix in place. Can you please test on a new install again. You can find the release 3.1.1 install file here: https://github.com/OraOpenSource/Logger/tree/3.1.1/releases

**Comment by miklpotter** [comment]
@martindsouza I installed 3.1.1 without any issues, and without needing to have select on sys.v_$parameter.
