### ISSUE TITLE
Execute permissions for dbms_lock

### ISSUE THREAD

**Issue by elewis33** [OraOpenSource/Logger#146]
I installed logger_3.1.0 yesterday and after installation completed successfully I ran some of the demos. When I ran demo_set_level I got an error indicating that the run_long_batch procedure had errors. It was because the user schema didn't have execute permissions on the sys.dbms_lock package. I'm wondering if this should be added to the permissions checks that are run prior to installation?

I'm also wondering if you might need to do some broader execute permissions checks for some of the other dbms_* packages that are used? Or are all of those done via the existing permissions checks?

**Comment by martindsouza** [comment]
Yes, the demo requires access to `sys.dbms_lock`. Since these are only demo scripts we won't be adding any additional permission checks as they are not installed in the DB (they're just scripts that you download).

For objects that are installed in the DB, permission checks are performed.

**Comment by elewis33** [comment]
OK, I was confused. I didn't realize (look closely enough) to see that the
demo script created the procedure that was not compiling. I thought that
was part of the installation script. My mistake.

I assume that procedure can be pulled out safely?

Earl

**Comment by martindsouza** [comment]
@elewis33 Yes, you can drop that procedure safely. It's just for demo purposes and no part of Logger relies on it.
