### ISSUE TITLE
Downloading Releases getting corrupt ZIP files

### ISSUE THREAD

**Issue by OliverLemm** [OraOpenSource/Logger#170]
When downloading a release by right-click on a ZIP file in the releases folder i get only corrupted releases.
When downloading the master including all releases the ZIP inside works.

**Comment by martindsouza** [comment]
@OliverLemm That's a GitHub thing. You need to click on the zip file and then click on the `Raw` button:

![image](https://cloud.githubusercontent.com/assets/2925726/15457982/7b410558-2051-11e6-9268-ec0b52635173.png)

The releases folder will be removed as part of #171
