### ISSUE TITLE
logger.rec_param when dealing varchar2 over 4000

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/Logger#176]
I had this function:

``` plsql
function get_select_list_html (
      p_query in varchar2
    ) return varchar2;
```

which passes a varchar2 of 32767. Then I had the usual

``` plsql
logger.append_param(l_params, 'p_query', p_query);
```

Only to realize that Logger was crashing because of `logger.rec_param`

``` plsql
type rec_param is record(
    name varchar2(255),
    val varchar2(4000));
```

Maybe we could increase `rec_param.val` to be `varchar2(32767)`?

**Comment by jeffreykemp** [comment]
Agreed.

**Comment by martindsouza** [comment]
Provided no performance issues we'll go ahead with it. I just need to write a test case to compare.

**Comment by patch72** [comment]
Since the column will be added to the CLOB, I don't expect any performance issues. Running with extended varchar2 size for a while on development with no performance issues found.

**Comment by martindsouza** [comment]
Test case:

```sql
declare
  l_text varchar2(4000) := :p_lorem_ipsum;
  l_params logger.tab_param;
  l_scope logger_logs.scope%type := 'test';
  l_params_empty logger.tab_param;
  c_loops constant number := 10;
begin
  
  -- Results
  -- 10000 = 44.943 w. vc2 4000
  -- 10000 = 43.028 w. vc2 32767
  for i in 1..c_loops loop
    logger.append_param(l_params, 'l_text', l_text);
    
    logger.log('START', l_scope, null, l_params);
    
    -- Reset l_params
    l_params := l_params_empty;
  end loop;
  
  
end;
/
```

No noticable difference. Will include the `val varchar2(val))` to `val varchar2(32767))`
