### ISSUE TITLE
Function to get the context for apex client session

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/Logger#181]
Will avoid developers having to code `:app_user : :app_session` themselves.

**Comment by SvenWeller** [comment]
Please be aware that it is highly dependend on the Apex version. In Apex 5 it should be read from the Apex context. The followin even works via DB links (because of the client identifier).

e.g.: coalesce(
          sys_context('APEX$SESSION','app_user')
         ,regexp_substr(sys_context('userenv','client_identifier'),'^[^:]*')
         ,sys_context('userenv','session_user')
         )

**Comment by martindsouza** [comment]
I think we can drop this ticket for now as it can be reference via `sys_context('userenv','client_identifier')` from within an APEX session. If we need to call elsewhere (i.e. setting the level for an APEX session) developers can just do `:app_user : :app_session` themselves. 

I haven't needed to do this enough to warrant writing a function for it.
