### ISSUE TITLE
logger.set_pref should be able to handle all configuration (both system and custom preferences)

### ISSUE THREAD

**Issue by JuergenSchuster** [OraOpenSource/Logger#184]
_Original title and description below._

Based on this ticket and feedback from @jeffreykemp I've renamed this ticket and re-defined its title. Goals:

- [x] Set all `LOGGER` (i.e. system level) preferences via the `logger.set_pref` method. This will make on consistent way for everyone to set preferences. Only exception is setting client specific levels. I don't see this as an issue.
- [x] Update the trigger on `logger_prefs` to ensure that no one updates `logger_prefs` unless its being called via `set_level`. An error should make note of the new update and to use `logger.set_pref`

**Original**
**Title: ** - Make clear that I can NOT just edit logger_prefs

I thought it is totally legit to edit the table directly instead of calling the APIs :-)

For example how should I set PREF_BY_CLIENT_ID_EXPIRE_HOURS? I don't find a API call to set this value.

**Comment by jeffreykemp** [comment]
There is no API call for this parameter as far as I can see - updating the table directly is the only way provided to change them. It seems to me the author made a conscious decision to specifically disallow updating the system-level preferences via the API.
