### ISSUE TITLE
Views LOGGER_LOGS_<interval> don't handle timezones correctly

### ISSUE THREAD

**Issue by frankschmitt** [OraOpenSource/Logger#199]
The views LOGGER_LOGS_<interval> (e.g. LOGGER_LOGS_60_MIN) don't handle timezones correctly.

To reproduce:
- set up a database server in an "early" timezone(e.g. San Francisco, UTC-7)
- add a log message with logger.log('debug message')
- query the view from a client located in the same timezone as the server
   => returns the log message
- query the view from a client located at least two timezones ahead (e.g. Berlin, UTC+2)
   => returns no messages

There are (at least) two possible ways to fix this - an easy but ugly workaround, and a "proper" fix:
- replace 
      	 where time_stamp > systimestamp - (1/24);
   with
	 where time_stamp > (cast (systimestamp as timestamp)) - (1/24);
   in the view definition. This forces conversion of systimestamp from TIMESTAMP WITH TIMEZONE to TIMESTAMP, therefore omitting all timezone information.
- use TIMESTAMP WITH TIMEZONE as data type for the LOGGER_LOGS.TIME_STAMP column. This is the proper solution, but this would probably break backward compatibility - introducing an additional column time_stamp_with_tz might be the better approach.

**Comment by martindsouza** [comment]
@frankschmitt thanks for logging and for the ideas. We'll look at either option 1 or 2. You're right about the third option in that we probably won't want to include the timezone on the timestamp.

**Comment by SvenWeller** [comment]
This is strange. Systimestamp should return the timezone from the server not the sessiontimezone. But there are multiple implicit conversions going on, which might use session nls settings.
I can't test it at the moment, but I think the problem is also related to "-1/24". Try "- interval '1' hour" instead.
It will return a timestamp_with_tz instead of a date.

**Comment by SvenWeller** [comment]
Or simply sysdate instead of systimestamp

**Comment by martindsouza** [comment]
I was unable to change the timezone in my DB as I got the following error message: `ORA-30079: cannot alter database timezone when database has TIMESTAMP WITH LOCAL TIME ZONE columns`

That said I decided to use the `cast (systimestamp as timestamp)` option. If this isn't good we can use @SvenWeller idea of using `sysdate`.
