### ISSUE TITLE
Event Level Identifier (from click to database)

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/Logger#53]
_From @theplaceboeffect on October 9, 2013 16:21_

What is the best way to create an identifier that can be carried over from a click on the database through all the relevant logging that was triggered by that click?

_Copied from original issue: tmuth/Logger---A-PL-SQL-Logging-Utility#52_

**Comment by martindsouza** [comment]
The easiest way would be to set the session's client identifier and filter on logger_logs.client_identifier. Note: if the "click" is done in APEX, don't set the client identifier as it will already be set for you.

This article describes how to set a client identifier: http://www.talkapex.com/2013/05/logger-200-enable-session-specific.html  It also highlights how to define session specific logging.

**Comment by p3t3r** [comment]
I'm still missing a level above the logger log lines. Of course you have the client identifier, but in an APEX session it is always the same for that session. 
If I code something, then run a test and look at the logging I can identify the log lines.
But if I then run a second test, there is not real distinction between the two test, maybe apart from the timestamps.  When running tests in quick succession, it's even more difficult.
