### ISSUE TITLE
Indent and timing Problem

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/Logger#73]
_From @B0N3 on July 7, 2014 9:4_

In "procedure time_stop" ~line 1003 the timer is deleted and g_running_timers decremented (this already happend in the function called in ~line 997).

The second bug that occurred on my end is tied to time zones. In "FUNCTION time_stop" the time delta was always off by 2 hours. My solution was saving the timestamp in a variable before using it to calculate the difference. I guess the same thing will be true for "FUNCTION time_stop_seconds", but i had no time testing it.

I am using the latest stable version 2.1.2

_Copied from original issue: tmuth/Logger---A-PL-SQL-Logging-Utility#72_

**Comment by TheLaxtSamurai** [comment]
I fixed this one in my local copy. any guidelines on how to contribute to this project?

**Comment by martindsouza** [comment]
Thanks for fixing this issue. To merge your changes into the project you'll need to fork the project, apply your changes, then do a pull request.

GitHub has an excellent guide on this entire process here: https://help.github.com/articles/using-pull-requests/

And to fork a project here: https://help.github.com/articles/fork-a-repo/

**Comment by martindsouza** [comment]
1st issue: fixed

2nd issue: I think this was occurring because the calculations were using `systimestamp` which included timezone information. However the the start time values did not include timezone information.
